version: '3'
services:
  db:
    build: ./mysql
    container_name: my_db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - "./mysql/init:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
    tty: true