version: '3'
services:
  db:
    build:
      context: ./docker/MySQL
    volumes:
      - "./docker/MySQL:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db2
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    container_name: my_db
    ports:
      - "3306:3306"
    tty: true